name: fail

on:
  workflow_dispatch:

#on:
  #push:
    #branches:
      #- master

jobs:
  fail:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Before Fail"

      - run: exit 1
        continue-on-error: true

      - run: echo "This Will Now Work"
