name: Run server performance stats

on:
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
      # Checkout your workflow repo
      - uses: actions/checkout@v4

      - run : echo "Before Fail"
      - run : exit 1 
      
      # Checkout server-performance-stats repo
      - uses: actions/checkout@v4
        with:
          repo: krishiupadhyay1535/server-performance-stats
          path: server-performance-stats

      # Run the script
      - name: Execute stats script
        run: |
          chmod +x server-performance-stats/server-performance-stats.sh
          bash server-performance-stats/server-performance-stats.sh
